###
https://agoi-api.herokuapp.com/ 
url = http://localhost:3002/


###################### STARTE ######################################

### => login
POST  http://localhost:3002/api/v1/auth/login
Content-Type: application/json

{
"mobile_number": 123456781,
"password": "password"
}


########## SHARE 


### Find All Stock
GET  http://localhost:3002/api/v1/stock/findAll/
Content-Type: application/json


### create stock
POST http://localhost:3002/api/v1/stock/create/
Content-Type: application/json

### postman

### edit by ID
not compleated

### delete by ID 
DELETE https://agoi-api.herokuapp.com/api/v1/stock/62d42cbc496b9458427a7ef3 

### get by ID

GET https://agoi-api.herokuapp.com/api/v1/stock/62d6f94e3192ca715c317031 HTTP/1.1

########## USER 

### get all
GET  https://agoi-api.herokuapp.com/api/v1/user 

### delete by Id 
DELETE http://localhost:3002/api/v1/user/:id

### get by ID
GET https://agoi-api.herokuapp.com/api/v1/user/62d83d8cf9e2a2fa687843f2 HTTP/1.1

### edit wallet balance by ID 
POST https://agoi-api.herokuapp.com/api/v1/user/edit-walate-amount/62d44229a4e2089d14020c4e
Content-Type: application/json

{
"wallet_balance": 60
}

########## KYC

### get all 

GET http://localhost:3002/api/v1/user/kyc/all HTTP/1.1

### get by ID 
GET http://localhost:3002/api/v1/user/kyc/62d83d8cf9e2a2fa687843f2


### change kyc statu  with reason 
POST https://agoi-api.herokuapp.com/api/v1/user/kyc/62da47fca3afc3ec3790de0d
Content-Type: application/json

{
    "is_kyc_approved": false,
    "kyc_feedback": "feedback (reasion of rejection)"
}

########## ORDER 

### get all
GET https://agoi-api.herokuapp.com/api/v1/user/order

### get all sell order

### get all  purchase order

### get order by ID 
GET http://localhost:3002/api/v1/user/order/ee306c630f51bc6da56301bb2a5fea5f HTTP/1.1

### change order status with reason 

########## NOTIFY USER 

###  Send notification to user (multipul)

### get notification history 

########## CASH OUT  ( after selling the order  generate a cash out )

### GET ALL  

### get by ID 

### change cash out status with reasion 

########## edit admin user  (logged in user in admin)    name email or password 
POST  http://localhost:3002/api/v1/user/editadmin
Content-Type: application/json

{
    "name": "user",
    "email_id": "user@user.com",
    "mobile_number": "1234"
}

######################### END #####################################
















### STOCK

### Create


### Find All

### sold-out-stocks
GET  http://localhost:3002/api/v1/stock/sold-out-stocks/
Content-Type: application/json

## sell-stock




POST http://localhost:3002/api/v1/stock/create/
Content-Type: application/json

{
"stock_sp_id": "2",
"stock_name": "HDFC Bank Ltd"
}

### Find all User

### KYC

### addKYC
POST  http://localhost:3002/api/v1/user/addKYC
Content-Type: application/json

{
"mobile_number": "1234",
"email_id": "ueser@user.com",
"demat_acc_no": "1234567890",
"pan_card_number": "KJID1233",
"pan_card_link": "string",
"account_number": "1234567890",
"account_number_link": "sting",
"aadhar_number": "1234567890",
"demat_screenshot": "string",
"nominee_name": "nameOfNominee",
"is_completed_profile": true,
"is_completed_kyc": true
}

### get all
### => Get All Purchase Order



### edit user admin details


### edit user admin details
GET  http://localhost:3002/api/v1/order
Content-Type: application/json

###Order

### create
POST http://localhost:3002/api/v1/user/createOrder
Content-Type: application/json

{
    "amount": "12",
    "csid": "62d83d8cf9e2a2fa687843f2",
    "csmail": "user@user.com",
    "csphone": "9090407368"
}

### Get All
GET  http://localhost:3002/api/v1/user/order
Content-Type: application/json

### avilable
GET http://localhost:3002/api/v1/user/order/available



### GET ORDER By order_id





























### other


### SHARE   

### Create share
POST http://localhost:3002/api/v1/share/create/
Content-Type: application/json

{
"share_id": "11",
"share_name": "test stock Name",
"cloudnery_id": "stirng",
"share_companyType": "company Type",
"face_value": "0",
"price_per_lot": 1,
"share_quantity": "2",
"share_discription": "stock discription",
"share_status": "Available",
"share_icon": "url ",
"avaiable_on": "NSDL"
}

###



### Find Share By Id
GET  http://localhost:3002/api/v1/share/62c0fd1f23eac2c9d19ab911
Content-Type: application/json

### Delete share By Id
DELETE   http://localhost:3002/api/v1/share/62c0fd2523eac2c9d19ab913
Content-Type: application/json


