###
https://agoi-api.herokuapp.com/ 
url = http://localhost:3002/


###################### STARTE ######################################

### => login
POST  http://localhost:3002/api/v1/auth/login
Content-Type: application/json

{
"mobile_number": 123456781,
"password": "password"
}


########## SHARE 


### Find All Stock
GET  http://localhost:3002/api/v1/stock/findAll/
Content-Type: application/json


### create stock
POST http://localhost:3002/api/v1/stock/create/
Content-Type: application/json

### postman

### edit only Icon by ID
POST http://localhost:3002/api/v1/stock/icon/edit/:id
Content-Type: multipart/form-data       

### edit only details 

not compleated

### delete by ID 
DELETE https://agoi-api.herokuapp.com/api/v1/stock/62d42cbc496b9458427a7ef3 

### get by ID

GET https://agoi-api.herokuapp.com/api/v1/stock/62d6f94e3192ca715c317031 HTTP/1.1

########## USER 

### get all
GET  https://agoi-api.herokuapp.com/api/v1/user 

### delete by Id 
DELETE http://localhost:3002/api/v1/user/:id

### get by ID
GET https://agoi-api.herokuapp.com/api/v1/user/62d83d8cf9e2a2fa687843f2 HTTP/1.1

### edit wallet balance by ID 
POST https://agoi-api.herokuapp.com/api/v1/user/edit-wallet/62d83d8cf9e2a2fa687843f2
Content-Type: application/json

{
"wallet_balance": 60
}

########## KYC

### get all 

GET http://localhost:3002/api/v1/user/kyc/all HTTP/1.1

### get by ID 
GET http://localhost:3002/api/v1/user/kyc/62d83d8cf9e2a2fa687843f2


### change kyc statu  with reason 
POST https://agoi-api.herokuapp.com/api/v1/user/kyc/62da47fca3afc3ec3790de0d
Content-Type: application/json

{
    "is_kyc_approved": false,
    "kyc_feedback": "feedback (reasion of rejection)"
}

########## ORDER 

### get all  sell+purchase order
GET http://localhost:3002/api/v1/user/order

### get all sell order
#sell stock entity
GET http://localhost:3002/api/v1/user/order/sell

### get all  purchase order
#new order  order entity
GET http://localhost:3002/api/v1/user/order/purchase
### get order by ID 
GET http://localhost:3002/api/v1/user/order/62d847c0b8c0d49c3b6f9bd4 HTTP/1.1

### change order status with reason 
POST https://agoi-api.herokuapp.com/api/v1/user/order/62d847c0b8c0d49c3b6f9bd4 
Content-Type: application/json
{
    "is_order_approved": true,
    "order_feedback": "Aman's order PC"
}

########## NOTIFY USER 

###  Send notification to user (multipul)
POST http://localhost:3002/api/v1/user/notify HTTP/1.1
Content-Type: application/json
{
    "userID": [
          {
            "id": "62da47fca3afc3ec3790de0d"
          },
           {
            "id": "62d8461c853c5d50e8222981"
          }
        ],
    "message": "Hello World"
}


### get notification history 

GET http://localhost:3002/api/v1/user/notify/all HTTP/1.1

########## CASH OUT  ( after selling the order  generate a cash out )

### GET ALL 


### get by ID 

### change cash out status with reasion 

########## edit admin user  (logged in user in admin)    name email or password 
POST  http://localhost:3002/api/v1/user/editadmin
Content-Type: application/json

{
    "name": "user",
    "email_id": "user@user.com",
    "mobile_number": "1234"
}

######################### END #####################################


































































##################################################################################################################################################









### STOCK

### Create


### Find All

### sold-out-stocks
GET  http://localhost:3002/api/v1/stock/sold-out-stocks/
Content-Type: application/json

## sell-stock




POST http://localhost:3002/api/v1/stock/create/
Content-Type: application/json

{
"stock_sp_id": "2",
"stock_name": "HDFC Bank Ltd"
}

### Find all User

### addKYC
POST  http://localhost:3002/api/v1/user/addKYC
Content-Type: application/json

{
"mobile_number": "1234",
"email_id": "ueser@user.com",
"demat_acc_no": "1234567890",
"pan_card_number": "KJID1233",
"pan_card_link": "string",
"account_number": "1234567890",
"account_number_link": "sting",
"aadhar_number": "1234567890",
"demat_screenshot": "string",
"nominee_name": "nameOfNominee",
"is_completed_profile": true,
"is_completed_kyc": true
}

### get all
### => Get All Purchase Order


###Order

### create
POST http://localhost:3002/api/v1/user/createOrder
Content-Type: application/json

{
    "amount": "12",
    "csid": "62d83d8cf9e2a2fa687843f2",
    "csmail": "user@user.com",
    "csphone": "9090407368"
}

### Get All
GET  http://localhost:3002/api/v1/user/order
Content-Type: application/json

### avilable
GET http://localhost:3002/api/v1/user/order/available
