 https://agoi-api.herokuapp.com/ 
url = http://localhost:3002/
### Home 
http://localhost:3002/api/v1/user/findAll/
GET {url}

### STOCK

### Create
POST http://localhost:3002/api/v1/stock/create/
Content-Type: application/json

{
"stock_sp_id": "3",
"stock_name": "HDFC Bank Ltd"
}

### Find All
GET  http://localhost:3002/api/v1/stock/available-stocks/
Content-Type: application/json

### sold-out-stocks
GET  http://localhost:3002/api/v1/stock/sold-out-stocks/
Content-Type: application/json

## sell-stock

### SHARE   

### Create share
POST http://localhost:3002/api/v1/share/create/
Content-Type: application/json

{
"share_id": "11",
"share_name": "test stock Name",
"cloudnery_id": "stirng",
"share_companyType": "company Type",
"face_value": "0",
"price_per_lot": 1,
"share_quantity": "2",
"share_discription": "stock discription",
"share_status": "Available",
"share_icon": "url ",
"avaiable_on": "NSDL"
}

###

### Find All SHARE
GET  http://localhost:3002/api/v1/share/findAll/
Content-Type: application/json

### Find Share By Id
GET  http://localhost:3002/api/v1/share/62c0fd1f23eac2c9d19ab911
Content-Type: application/json

### Delete share By Id
DELETE   http://localhost:3002/api/v1/share/62c0fd2523eac2c9d19ab913
Content-Type: application/json

### Find all User
GET  http://localhost:3002/api/v1/user/findAll/

###

POST http://localhost:3002/api/v1/stock/create/
Content-Type: application/json

{
"stock_sp_id": "2",
"stock_name": "HDFC Bank Ltd"
}

### Find all User
GET  http://localhost:3002/api/v1/user/findAll/

###

### KYC

### get all
GET http://localhost:3002/api/v1/user/getallKYC

### get by ID
GET http://localhost:3002/api/v1/user/getKYC/62d44229a4e2089d14020c4e

### => Get All Purchase Order

### => login
POST  http://localhost:3002/api/v1/auth/login
Content-Type: application/json

{
"mobile_number": 123456789,
"password": "password"
}